### ISSUE TITLE
css单行和多行截断

### ISSUE THREAD

**Issue by rancho-xjq** [rancho-xjq/web-knowledge#51]
- 单行
``` css
.text-flow {
  overflow:hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```
